version: '3.8'

services:
  # Express.js Node.js application
  api:
    container_name: superlist-api
    build: ./api
    ports:
      - "3100:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

  # React 19 frontend application
  app:
    container_name: superlist-app
    build: ./app
    ports:
      - "3200:3200"
    depends_on:
      - api
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev

  # MongoDB database
  mongodb:
    container_name: superlist-mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: